platform :ios, '15.0'

target 'DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp
  pod 'dojo-ios-sdk', :git => 'https://github.com/dojo-engineering/dojo-ios-sdk.git', :tag => '1.4.5'
  pod 'dojo-ios-sdk-drop-in-ui', :path => '../'
  pod 'CocoaDebug', :configurations => ['Debug'] #network trafic tool


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
               end
          end
   end
end
end
