use_frameworks!

platform :ios, '11.0'

target 'dojo-ios-sdk-drop-in-ui_Example' do
  pod 'dojo-ios-sdk', :git => 'git@github.com:Dojo-Engineering/dojo-ios-sdk.git', :tag => '0.3.0'
  pod 'dojo-ios-sdk-drop-in-ui', :path => '../'

  target 'dojo-ios-sdk-drop-in-ui_Tests' do
    inherit! :search_paths

    
  end
end
